version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: angular.Dockerfile
    container_name: angular-dev
    volumes:
      - ./angular-app:/app
      - /app/node_modules
    ports:
      - "14281:4200"
    environment:
      - NODE_ENV=development
    command: npm start
    working_dir: /app

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./angular-app/dist/browser:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "14280:80"
    depends_on:
      - angular